### ISSUE TITLE
[Bug]: Cobblebreaker crash

### ISSUE THREAD

**Issue by Zeldown** [Paladium-Developpement/Paladium-Issue#119]
### Pseudo InGame

Zeldown

### Que s'est-il passé ?

Lorsque l'on rentre dans dans un chunk le jeu crash

### Serveur

Saharia

### LOG

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 04/01/22 14:10
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at fr.paladium.IiiiIiiiiiiiIiI.func_149673_e(wt:174)
	at fr.paladium.IiiIiiiiiiiIIiI.func_149673_e(uq:119)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6672)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4788)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fr.paladium.IiiiIiiiiiiiIiI.func_149673_e(wt:174)
	at fr.paladium.IiiIiiiiiiiIIiI.func_149673_e(uq:119)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6672)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4788)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LaTerreur06'/321801, l='MpServer', x=-6992,89, y=46,39, z=1532,57]]
	Chunk stats: MultiplayerChunkCache: 29, 60
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,78,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 286653240 game time, 53614063 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 16 total; [EntityOtherPlayerMP['R4OUF'/6048523, l='MpServer', x=0,00, y=78,00, z=0,00], EntityOtherPlayerMP['R4OUF'/6048523, l='MpServer', x=0,00, y=78,00, z=0,00], EntityItem['item.tile.dirt.default'/6049378, l='MpServer', x=-6983,59, y=58,13, z=1538,13], EntityOtherPlayerMP['R4OUF'/6048523, l='MpServer', x=0,00, y=78,00, z=0,00], EntityOtherPlayerMP['Raphael_3005'/6047370, l='MpServer', x=0,00, y=78,00, z=0,00], EntityClientPlayerMP['LaTerreur06'/321801, l='MpServer', x=-6992,89, y=46,39, z=1532,57], EntityOtherPlayerMP['R4OUF'/6048523, l='MpServer', x=0,00, y=78,00, z=0,00], EntitySkeleton['Skeleton'/103248, l='MpServer', x=-1,30, y=-28,66, z=-13,54], EntitySkeleton['Skeleton'/156893, l='MpServer', x=1,70, y=-19,93, z=-13,40], EntityOtherPlayerMP['ChevalierBoy'/6049219, l='MpServer', x=-4,13, y=77,00, z=-28,69], EntityOtherPlayerMP['Brafper'/6047919, l='MpServer', x=-12,61, y=77,50, z=14,33], EntityOtherPlayerMP['exnil1'/6047254, l='MpServer', x=-10,72, y=77,00, z=9,06], EntityOtherPlayerMP['kurama_fab11'/6048040, l='MpServer', x=24,44, y=77,00, z=-8,50], EntityOtherPlayerMP['Raphael_3005'/6047370, l='MpServer', x=0,00, y=78,00, z=0,00], EntityOtherPlayerMP['Brafper'/6047919, l='MpServer', x=-26,13, y=79,01, z=-29,50], EntityOtherPlayerMP['Fiaf24'/5991286, l='MpServer', x=4,75, y=77,00, z=-26,59]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2443)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5439608536 bytes (5187 MB) / 6576668672 bytes (6272 MB) up to 6979321856 bytes (6656 MB)
	JVM Flags: 9 total; -Xms512M -Xmx6656M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (beaaadcc5114ba2cbd30a46663759c6f7c1033be171dab602a824b2068deda0c) 
	UCHIJA	CarpentersBlocks{3.2.8.7} [Carpenter's Blocks] (29ffadfdc5fbcf7063d831112eecf57e038c7bf7af7d4cf486336c6ef140baef) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (32b73a01e91256aee7ea92fe4e33f17eaa42914111f129a2e2427921447fcbf7) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (dfe1f7022afddb09a46100298a06b70e1b4805be2f03901c270d8758d5b09e35) 
	UCHIJA	props{2.4.2} [Decocraft] (dfe1f7022afddb09a46100298a06b70e1b4805be2f03901c270d8758d5b09e35) 
	UCHIJA	palamod{7.6.0.0} [PalaMod] (aef2dd854f8512790301bd754dce232b1def54c27b7693b4689e331c5f52bb49) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (30722a5711603c1984b579ad4b60ee4dd1a3eee25d33fe49b08c5cc24937394c) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (f86fdb9d517f3107ddcba66976a319ac68eb95687e999a9f1dadf4fd9cd2d36e) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (4be2054d3ca56ee86be49c66e632ac752d7528bb3148baae9f50a18216b953f8) 
	UCHIJA	StorageDrawers{1.7.10-1.10.11} [Storage Drawers] (ddc41df8fd394da0fdb4f805ed82a1777d223fb713be97c40c3d4e6fc5fa3826) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (58385363ce4632adb117979a89745f451bceac409fd083e17303b20ed8cd9cdb) 
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithfull_paladium_officiel.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
