### ISSUE TITLE
[Bug]: Crash Quête Palapass

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1884]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Depuis le changement du Palapass du mois d'avril , tous les joueurs crash lorsqu'ils essaient d'accèder à leur quêtes.

### Rec

.

### Serveur

None

### LOG

Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at fr.paladium.palapass.client.ui.node.PalapassIconNode.init(PalapassIconNode.java:30)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:147)
	at fr.paladium.zephyrui.lib.ui.node.Node.append(Node.java:495)
	at fr.paladium.zephyrui.lib.ui.node.Node.attach(Node.java:511)
	at fr.paladium.palapass.client.ui.popup.quest.node.PalapassQuestNode.init(PalapassQuestNode.java:82)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:147)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.core.UI.add(UI.java:946)
	at fr.paladium.zephyrui.lib.ui.node.Node.attach(Node.java:524)
	at fr.paladium.palapass.client.ui.popup.quest.UIPalapassQuestPopup.init(UIPalapassQuestPopup.java:352)
	at fr.paladium.zephyrui.lib.ui.core.UI.load(UI.java:157)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.add(GuiBridge.java:302)
	at fr.paladium.zephyrui.lib.ui.core.UI.open(UI.java:837)
	at fr.paladium.palapass.client.ui.UIPalapass.lambda$init$0(UIPalapass.java:132)
	at fr.paladium.palapass.client.ui.UIPalapass$$Lambda$385/1081233514.accept(Unknown Source)
	at fr.paladium.zephyrui.lib.ui.node.Node.executeCallback(Node.java:639)
	at fr.paladium.zephyrui.lib.ui.node.Node.onMousePressed(Node.java:339)
	at fr.paladium.zephyrui.lib.ui.core.UI.onMousePressed(UI.java:252)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.func_73864_a(GuiBridge.java:79)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.func_146274_d(GuiBridge.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:974)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:900)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fr.paladium.palapass.client.ui.node.PalapassIconNode.init(PalapassIconNode.java:30)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:147)
	at fr.paladium.zephyrui.lib.ui.node.Node.append(Node.java:495)
	at fr.paladium.zephyrui.lib.ui.node.Node.attach(Node.java:511)
	at fr.paladium.palapass.client.ui.popup.quest.node.PalapassQuestNode.init(PalapassQuestNode.java:82)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:147)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node.lambda$load$0(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.node.Node$$Lambda$346/571960146.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at fr.paladium.zephyrui.lib.ui.node.Node.load(Node.java:142)
	at fr.paladium.zephyrui.lib.ui.core.UI.add(UI.java:946)
	at fr.paladium.zephyrui.lib.ui.node.Node.attach(Node.java:524)
	at fr.paladium.palapass.client.ui.popup.quest.UIPalapassQuestPopup.init(UIPalapassQuestPopup.java:352)
	at fr.paladium.zephyrui.lib.ui.core.UI.load(UI.java:157)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.add(GuiBridge.java:302)
	at fr.paladium.zephyrui.lib.ui.core.UI.open(UI.java:837)
	at fr.paladium.palapass.client.ui.UIPalapass.lambda$init$0(UIPalapass.java:132)
	at fr.paladium.palapass.client.ui.UIPalapass$$Lambda$385/1081233514.accept(Unknown Source)
	at fr.paladium.zephyrui.lib.ui.node.Node.executeCallback(Node.java:639)
	at fr.paladium.zephyrui.lib.ui.node.Node.onMousePressed(Node.java:339)
	at fr.paladium.zephyrui.lib.ui.core.UI.onMousePressed(UI.java:252)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.func_73864_a(GuiBridge.java:79)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at fr.paladium.zephyrui.internal.bridge.client.gui.GuiBridge.func_146274_d(GuiBridge.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

**Comment by aureliancnx** [comment]
Bonjour, ce bug a été pris en charge
