### ISSUE TITLE
[Bug]: Crash client rendering Item

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#400]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 06/06/22 10:49
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:159)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at fr.paladium.lib.apollon.utils.GuiUtils.renderItemStackIntoGUI(GuiUtils.java:759)
	at fr.paladium.lib.apollon.utils.GuiUtils.renderScaledItemStackIntoGUI(GuiUtils.java:788)
	at fr.paladium.lib.apollon.notification.FlatNotification.draw(FlatNotification.java:114)
	at fr.paladium.lib.apollon.ApollonEvent.lambda$onRenderNotification$0(ApollonEvent.java:39)
	at fr.paladium.lib.apollon.ApollonEvent$$Lambda$186/1153343358.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at fr.paladium.lib.apollon.ApollonEvent.onRenderNotification(ApollonEvent.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_ApollonEvent_onRenderNotification_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:909)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:159)

-- Item being rendered --
Details:
	Item Type: null
	Item Aux: ~~ERROR~~ NullPointerException: null
	Item NBT: null
	Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at fr.paladium.lib.apollon.utils.GuiUtils.renderItemStackIntoGUI(GuiUtils.java:759)
	at fr.paladium.lib.apollon.utils.GuiUtils.renderScaledItemStackIntoGUI(GuiUtils.java:788)
	at fr.paladium.lib.apollon.notification.FlatNotification.draw(FlatNotification.java:114)
	at fr.paladium.lib.apollon.ApollonEvent.lambda$onRenderNotification$0(ApollonEvent.java:39)
	at fr.paladium.lib.apollon.ApollonEvent$$Lambda$186/1153343358.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at fr.paladium.lib.apollon.ApollonEvent.onRenderNotification(ApollonEvent.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_ApollonEvent_onRenderNotification_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:909)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LeVraiFuze'/3238600, l='MpServer', x=1235,65, y=5,62, z=1222,90]]
	Chunk stats: MultiplayerChunkCache: 40, 159
	Level seed: 0
	Level generator: ID 04 - TerrainControl, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,99,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4976622 game time, 4987562 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityItem['item.tile.stonebrick'/4315485, l='MpServer', x=1234,78, y=4,13, z=1209,84], EntityItem['item.tile.stonebrick'/4316265, l='MpServer', x=1234,46, y=5,14, z=1216,28], EntityItem['item.tile.stonebrick'/4316264, l='MpServer', x=1234,68, y=4,83, z=1215,42], EntityItem['item.tile.stonebrick'/4316267, l='MpServer', x=1234,55, y=5,78, z=1215,81], EntityItem['item.tile.stonebrick'/4316266, l='MpServer', x=1234,78, y=5,55, z=1215,73], EntityItem['item.tile.stonebrick'/4316269, l='MpServer', x=1234,30, y=3,75, z=1217,64], EntityItem['item.tile.stonebrick'/4316268, l='MpServer', x=1234,37, y=4,69, z=1217,73], EntityItem['item.tile.stonebrick'/4316271, l='MpServer', x=1234,13, y=4,16, z=1215,22], EntityItem['item.tile.stonebrick'/4316270, l='MpServer', x=1234,37, y=3,63, z=1216,16], EntityItem['item.tile.titane.ore'/4316273, l='MpServer', x=1234,33, y=3,97, z=1213,33], EntityItem['item.tile.stonebrick'/4316272, l='MpServer', x=1234,62, y=3,78, z=1215,06], EntityItem['item.tile.stonebrick'/4316275, l='MpServer', x=1235,36, y=5,10, z=1213,88], EntityItem['item.tile.stonebrick'/4316274, l='MpServer', x=1235,46, y=4,81, z=1212,31], EntityItem['item.tile.stonebrick'/4316277, l='MpServer', x=1235,76, y=5,48, z=1212,26], EntityItem['item.tile.stonebrick'/4316276, l='MpServer', x=1235,60, y=4,03, z=1213,42], EntityItem['item.tile.stonebrick'/4315510, l='MpServer', x=1234,19, y=4,13, z=1208,50], EntityClientPlayerMP['LeVraiFuze'/3238600, l='MpServer', x=1235,65, y=5,62, z=1222,90], EntityOtherPlayerMP['Blushney'/4236682, l='MpServer', x=-5,38, y=168,00, z=0,00], EntityOtherPlayerMP['AnyDox'/4221389, l='MpServer', x=-0,31, y=167,00, z=-6,53], EntityOtherPlayerMP['SIMYYI'/4234981, l='MpServer', x=9,59, y=169,00, z=-6,66], EntityItem['item.tile.stonebrick'/4315669, l='MpServer', x=1234,13, y=3,13, z=1215,40], EntityItem['item.tile.stonebrick'/4315674, l='MpServer', x=1234,81, y=3,13, z=1215,42], EntityCaveSpider['Cave Spider'/825709, l='MpServer', x=1,73, y=-0,00, z=-45,48], EntityCaveSpider['Cave Spider'/62839, l='MpServer', x=26,08, y=-0,00, z=-41,36], EntityItem['item.tile.stonebrick'/4315584, l='MpServer', x=1234,88, y=4,13, z=1212,80], EntityItem['item.tile.stonebrick'/4315601, l='MpServer', x=1234,13, y=4,13, z=1212,61], EntityItem['item.tile.stonebrick'/4315619, l='MpServer', x=1234,88, y=3,13, z=1213,23], EntityItem['item.tile.stonebrick'/4315636, l='MpServer', x=1234,79, y=4,13, z=1212,96], EntityCaveSpider['Cave Spider'/87222, l='MpServer', x=37,73, y=-0,09, z=-18,45], EntityCaveSpider['Cave Spider'/1273562, l='MpServer', x=10,30, y=-0,09, z=7,00], EntityItem['item.tile.stonebrick'/4315538, l='MpServer', x=1234,13, y=4,13, z=1210,57], EntityItem['item.tile.stonebrick'/4315541, l='MpServer', x=1234,22, y=4,13, z=1212,01], EntityItem['item.tile.stonebrick'/4315551, l='MpServer', x=1234,88, y=4,13, z=1212,27]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2443)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:920)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 779489936 bytes (743 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 11 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx6G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (beaaadcc5114ba2cbd30a46663759c6f7c1033be171dab602a824b2068deda0c) 
	UCHIJA	apollon{4.2.18} [Apollon] (cde433b266f6c0a02fc7ab8f72168567a7e1dc5685642d780912fe2399d10cfb) 
	UCHIJA	backtothefuture{1.0} [Back to the future] (d470b0da7646576b94419d4668ba3062afeabec2637866e280e39b8f472790a3) 
	UCHIJA	customnpcs{1.5.4} [CustomNpcs] (32b73a01e91256aee7ea92fe4e33f17eaa42914111f129a2e2427921447fcbf7) 
	UCHIJA	factions{0.1} [Factions] (c372c1ffdafcfa9eca3b9e5849f8496d483fe8a86ed0a6b14c65f76f555583e0) 
	UCHIJA	palamod{7.6.1.2} [PalaMod] (aef2dd854f8512790301bd754dce232b1def54c27b7693b4689e331c5f52bb49) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (30722a5711603c1984b579ad4b60ee4dd1a3eee25d33fe49b08c5cc24937394c) 
	UCHIJA	helios{2.3.0} [Helios Mod] (0f3692ee8133b5fc77da79257d746ca5e71c06078d2795cf55f4861f26aeedd0) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (f86fdb9d517f3107ddcba66976a319ac68eb95687e999a9f1dadf4fd9cd2d36e) 
	UCHIJA	common{1.0} [Paladium Common] (ea3e31803e033a4824f9edc2b4b2a8af405a0ff38211a0e2bf0ce2a9d4c42060) 
	UCHIJA	palagamemod{1.0} [PalaGame Mod] (f11998c6db2d9288efb43fb31b9cde18d39cb12310a3aa8ecdf5f8be0dc8a468) 
	UCHIJA	StorageDrawers{1.7.10-1.10.11} [Storage Drawers] (ddc41df8fd394da0fdb4f805ed82a1777d223fb713be97c40c3d4e6fc5fa3826) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (58385363ce4632adb117979a89745f451bceac409fd083e17303b20ed8cd9cdb) 
	Pulsar/common loaded Pulses: 
		- common-cosmetics (Enabled/Forced)
		- common-boutique (Enabled/Forced)
		- common-armourers (Enabled/Forced)
		- common-common (Enabled/Forced)

	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.09
	OpenGlRenderer: GeForce RTX 3080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
