### ISSUE TITLE
[Bug]: Crash client

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#401]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

---- Minecraft Crash Report ----
// There are four lights!

Time: 06/06/22 10:59
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.item.ItemStack.func_150999_a(ItemStack.java:313)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1356)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1966)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:972)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_150999_a(ItemStack.java:313)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1356)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LeVraiFuze'/89, l='MpServer', x=12453,17, y=40,62, z=3719,36]]
	Chunk stats: MultiplayerChunkCache: 51, 81
	Level seed: 0
	Level generator: ID 04 - TerrainControl, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,158,0), Chunk: (at 0,9,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5481807 game time, 5492747 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['LeVraiFuze'/89, l='MpServer', x=12453,17, y=40,62, z=3719,36]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2443)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 606074208 bytes (577 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 11 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx6G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (beaaadcc5114ba2cbd30a46663759c6f7c1033be171dab602a824b2068deda0c) 
	UCHIJA	apollon{4.2.18} [Apollon] (cde433b266f6c0a02fc7ab8f72168567a7e1dc5685642d780912fe2399d10cfb) 
	UCHIJA	backtothefuture{1.0} [Back to the future] (d470b0da7646576b94419d4668ba3062afeabec2637866e280e39b8f472790a3) 
	UCHIJA	customnpcs{1.5.4} [CustomNpcs] (32b73a01e91256aee7ea92fe4e33f17eaa42914111f129a2e2427921447fcbf7) 
	UCHIJA	factions{0.1} [Factions] (c372c1ffdafcfa9eca3b9e5849f8496d483fe8a86ed0a6b14c65f76f555583e0) 
	UCHIJA	palamod{7.6.1.2} [PalaMod] (aef2dd854f8512790301bd754dce232b1def54c27b7693b4689e331c5f52bb49) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (30722a5711603c1984b579ad4b60ee4dd1a3eee25d33fe49b08c5cc24937394c) 
	UCHIJA	helios{2.3.0} [Helios Mod] (0f3692ee8133b5fc77da79257d746ca5e71c06078d2795cf55f4861f26aeedd0) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (f86fdb9d517f3107ddcba66976a319ac68eb95687e999a9f1dadf4fd9cd2d36e) 
	UCHIJA	common{1.0} [Paladium Common] (ea3e31803e033a4824f9edc2b4b2a8af405a0ff38211a0e2bf0ce2a9d4c42060) 
	UCHIJA	palagamemod{1.0} [PalaGame Mod] (f11998c6db2d9288efb43fb31b9cde18d39cb12310a3aa8ecdf5f8be0dc8a468) 
	UCHIJA	StorageDrawers{1.7.10-1.10.11} [Storage Drawers] (ddc41df8fd394da0fdb4f805ed82a1777d223fb713be97c40c3d4e6fc5fa3826) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (58385363ce4632adb117979a89745f451bceac409fd083e17303b20ed8cd9cdb) 
	Pulsar/common loaded Pulses: 
		- common-cosmetics (Enabled/Forced)
		- common-boutique (Enabled/Forced)
		- common-armourers (Enabled/Forced)
		- common-common (Enabled/Forced)

	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.09
	OpenGlRenderer: GeForce RTX 3080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by aureliancnx** [comment]
Cette erreur ayant l'air de venir de Minecraft, nous ne pouvons pas proposer un fix dans l'immédiat
