### ISSUE TITLE
[Bug]: Crash lors du loot d'un item

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#668]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

report d'un joueur, SK0R3N, lorsqu'il ramasse n'importe quel item le jeu crash.

REC: https://www.youtube.com/watch?v=CZcW5gqEETY&ab_channel=Sebastien

Date 31/07/2022 21h00

### LOG

[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/goat/neytoxss/goat_death.ogg does not exist, cannot add it to event palamod:mob.goat.neytoxss.death
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/goat/neytoxss/goat_hurt.ogg does not exist, cannot add it to event palamod:mob.goat.neytoxss.hurt
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/goat/neytoxss/goat_living.ogg does not exist, cannot add it to event palamod:mob.goat.neytoxss.living
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/jellyfish/neytoxss/jellyfish_death.ogg does not exist, cannot add it to event palamod:mob.jellyfish.neytoxss.death
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/jellyfish/neytoxss/jellyfish_hurt.ogg does not exist, cannot add it to event palamod:mob.jellyfish.neytoxss.hurt
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/jellyfish/neytoxss/jellyfish_living.ogg does not exist, cannot add it to event palamod:mob.jellyfish.neytoxss.living
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/parrot/neytoxss/parrot_death.ogg does not exist, cannot add it to event palamod:mob.parrot.neytoxss.death
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/parrot/neytoxss/parrot_hurt.ogg does not exist, cannot add it to event palamod:mob.parrot.neytoxss.hurt
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/parrot/neytoxss/parrot_living.ogg does not exist, cannot add it to event palamod:mob.parrot.neytoxss.living
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/snail/neytoxss/snail_death.ogg does not exist, cannot add it to event palamod:mob.snail.neytoxss.death
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/snail/neytoxss/snail_hurt.ogg does not exist, cannot add it to event palamod:mob.snail.neytoxss.hurt
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/snail/neytoxss/snail_living.ogg does not exist, cannot add it to event palamod:mob.snail.neytoxss.living
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/turtle/neytoxss/turtle_death.ogg does not exist, cannot add it to event palamod:mob.turtle.neytoxss.death
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/turtle/neytoxss/turtle_hurt.ogg does not exist, cannot add it to event palamod:mob.turtle.neytoxss.hurt
[15:09:33] [Client thread/WARN]: File palamod:sounds/mob/turtle/neytoxss/turtle_living.ogg does not exist, cannot add it to event palamod:mob.turtle.neytoxss.living
[15:09:33] [Thread-22/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[15:09:33] [Client thread/INFO]: [fr.paladium.lib.apollon.fontV2.FontRenderer:<clinit>:98]: loaded
[15:09:33] [Client thread/INFO]: [OptiFine] *** Reloading custom textures ***
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: textures/colormap/grass.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: textures/colormap/foliage.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/swampgrass.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/swampfoliage.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/sky0.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/fog0.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/underwater.png
[15:09:33] [Client thread/INFO]: [OptiFine] Loading mcpatcher/color.properties
[15:09:33] [Client thread/INFO]: [OptiFine] Custom color: drop.water = 93b9f1
[15:09:33] [Client thread/INFO]: [OptiFine] Custom color: fog.nether = 4d0b0b
[15:09:33] [Client thread/INFO]: [OptiFine] Custom color: fog.end = 150018
[15:09:33] [Client thread/INFO]: [OptiFine] Custom color: sky.end = 000000
[15:09:33] [Client thread/INFO]: [OptiFine] Block palette: palette.block.~/colormap/stone.png = 1 4 13 14 15 16 21 23 24 29 33 43:0 43:1 43:3 43:5 44:0 44:1 44:3 44:5 48 56 61 62 67 70 73 74 82 93 94 97 98 109 128 129 139 158
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/stone.png
[15:09:33] [Client thread/INFO]: [OptiFine] Block palette: palette.block.~/colormap/sand.png = 12
[15:09:33] [Client thread/INFO]: [OptiFine] Loading custom colors: mcpatcher/colormap/sand.png
[15:09:33] [Client thread/INFO]: [OptiFine] CustomSky properties: mcpatcher/sky/world0/sky1.properties
[15:09:33] [Client thread/INFO]: [OptiFine] CustomSky properties: mcpatcher/sky/world0/sky2.properties
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/cow/cow.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/creeper/creeper.png, variants: 4
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/enderman/enderman_eyes.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/ghast/ghast.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/ghast/ghast_shooting.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/iron_golem.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/pig/pig.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/silverfish.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/skeleton/skeleton.png, variants: 4
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/slime/magmacube.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/spider/spider.png, variants: 3
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/squid.png, variants: 6
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/wolf/wolf.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/wolf/wolf_angry.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/wolf/wolf_tame.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/zombie_pigman.png, variants: 2
[15:09:33] [Client thread/INFO]: [OptiFine] RandomMobs: textures/entity/zombie/zombie.png, variants: 9
[15:09:33] [Client thread/INFO]: [OptiFine] Texture pack clouds: fast
[15:09:33] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[15:09:33] [Sound Library Loader/INFO]: Sound engine started
[15:09:34] [Thread-27/INFO]: [fr.paladium.lib.apollon.nodes.abstracts.ANode$DownloadImage:run:432]: BufferedImage@7ff78ac: type = 6 ColorModel: #pixelBits = 32 numComponents = 4 color space = java.awt.color.ICC_ColorSpace@3c0fc8b transparency = 3 has alpha = true isAlphaPre = false ByteInterleavedRaster: width = 1920 height = 1080 #numDataElements 4 dataOff[0] = 3
[15:09:34] [Thread-28/INFO]: [fr.paladium.lib.apollon.nodes.abstracts.ANode$DownloadImage:run:432]: BufferedImage@1c204eed: type = 6 ColorModel: #pixelBits = 32 numComponents = 4 color space = java.awt.color.ICC_ColorSpace@3c0fc8b transparency = 3 has alpha = true isAlphaPre = false ByteInterleavedRaster: width = 1920 height = 1080 #numDataElements 4 dataOff[0] = 3
[15:16:12] [Netty Client IO #0/INFO]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, apollon, backtothefuture, cresus, customnpcs, factions, guardiangolem, helios, IronChest, common, palagamemod, palamod, secretroomsmod, StorageDrawers, TerrainControl] at SERVER
[15:16:13] [Client thread/INFO]: Connecting to mc.paladium-pvp.fr, 25565
[15:16:14] [Client thread/INFO]: Connecting to paladium (mc.paladium-pvp.fr:25565)
[15:16:15] [Netty Client IO #2/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S02PacketChat
[15:16:15] [Netty Client IO #2/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S02PacketChat
[15:16:15] [Netty Client IO #2/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S02PacketChat
[15:16:15] [Client thread/INFO]: [CHAT] Connected to LOBBY-6d94f16d-b780-41f5-aa59-ff56e427cc1c
[15:16:15] [Client thread/INFO]: [CHAT] §e[Amis] §7Aucun ami en ligne
[15:16:15] [Client thread/INFO]: [CHAT] 
[15:16:16] [Netty Client IO #2/INFO]: Server protocol version 2
[15:16:16] [Netty Client IO #2/INFO]: Attempting connection with missing mods [CodeChickenCore, NotEnoughItems, cresus, customnpcs, factions, guardiangolem, IronChest, palamod, secretroomsmod, StorageDrawers, TerrainControl] at SERVER
[15:16:16] [Netty Client IO #2/INFO]: Injecting existing block and item data into this client instance
[15:16:16] [Netty Client IO #2/INFO]: Applying holder lookups
[15:16:16] [Netty Client IO #2/INFO]: Holder lookups applied
[15:16:16] [Client thread/INFO]: [Client thread] Client side modded connection established
[15:16:16] [Client thread/INFO]: [fr.paladium.IIiiIiiiiiIiIii:Go:189]: Patching Chunk Loading
[15:16:17] [Thread-9/INFO]: [CHAT] §2CustomNpcs§f installed. For more info §9§nClick here
[15:16:18] [Client thread/INFO]: [CHAT] Version 1.0.7.48 of CodeChickenCore is available
[15:16:18] [Client thread/INFO]: [CHAT] Version 1.0.5.120 of NotEnoughItems is available
[15:16:18] [Client thread/INFO]: [Shaders] usedColorBuffers: 4
[15:16:18] [Client thread/INFO]: [Shaders] usedDepthBuffers: 1
[15:16:18] [Client thread/INFO]: [Shaders] usedShadowColorBuffers: 0
[15:16:18] [Client thread/INFO]: [Shaders] usedShadowDepthBuffers: 0
[15:16:18] [Client thread/INFO]: [Shaders] usedColorAttachs: 4
[15:16:18] [Client thread/INFO]: [Shaders] usedDrawBuffers: 1
[15:16:18] [Client thread/INFO]: [Shaders] Framebuffer created.
[15:16:18] [Client thread/INFO]: [Shaders] Reset world renderers
[15:16:19] [Client thread/INFO]: [Shaders] Reset model renderers
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:23] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:25] [Client thread/INFO]: [Shaders] Framebuffer created.
[15:16:26] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:28] [Netty Client IO #2/INFO]: Applying holder lookups
[15:16:28] [Netty Client IO #2/INFO]: Holder lookups applied
[15:16:28] [Netty Client IO #2/INFO]: Server protocol version 2
[15:16:28] [Netty Client IO #2/INFO]: Attempting connection with missing mods [CodeChickenCore, NotEnoughItems, palagamemod] at SERVER
[15:16:29] [Netty Client IO #2/INFO]: Injecting existing block and item data into this client instance
[15:16:29] [Netty Client IO #2/INFO]: Applying holder lookups
[15:16:29] [Netty Client IO #2/INFO]: Holder lookups applied
[15:16:29] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[15:16:29] [Client thread/INFO]: [Client thread] Client side modded connection established
[15:16:29] [Client thread/INFO]: [fr.paladium.IIiiIiiiiiIiIii:Go:189]: Patching Chunk Loading
[15:16:30] [Client thread/INFO]: [CHAT] §c[§4PalaTrade§c] §r §6You §6have §6joined §6a §6new §6server, §6your §6trade §6requests §6have §6been §6§areactivated§6! §6Press §6§b'P'§6or §6type §6§b/trade §6§6to §6open §6the §6§cPalaTrade §6§6configuration §6menu.palatrade.tradeaccepted= §6Your §6trade §6request §6has §6been §6§aaccepted§6! §6Opening §6of §6the §6trade §6window! 
[15:16:30] [Client thread/INFO]: [TerrainControl] [INFO] Config received from server
[15:16:30] [Client thread/INFO]: [Shaders] Expand tesselator buffer 1048576
[15:16:33] [Client thread/INFO]: Applying holder lookups
[15:16:33] [Client thread/INFO]: Holder lookups applied
[15:16:34] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1489) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.Arrays.fill(Arrays.java:2903) ~[?:1.8.0_51]
	at shadersmod.client.ShadersTex.initDynamicTexture(ShadersTex.java:288) ~[ShadersTex.class:?]
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(DynamicTexture.java:42) ~[bpq.class:?]
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:28) ~[DynamicEditableTexture.class:?]
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:21) ~[DynamicEditableTexture.class:?]
	at fr.paladium.factions.client.map.gui.UIFactionMap.drawMapLayer(UIFactionMap.java:396) ~[UIFactionMap.class:?]
	at fr.paladium.factions.client.map.gui.UIFactionMap.preDraw(UIFactionMap.java:229) ~[UIFactionMap.class:?]
	at fr.paladium.lib.apollon.ui.UI.func_73863_a(UI.java:196) ~[UI.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455) ~[blt.class:?]
	... 9 more
[15:16:35] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 7/31/22 3:16 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.util.Arrays.fill(Arrays.java:2903)
	at shadersmod.client.ShadersTex.initDynamicTexture(ShadersTex.java:288)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(DynamicTexture.java:42)
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:28)
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:21)
	at fr.paladium.factions.client.map.gui.UIFactionMap.drawMapLayer(UIFactionMap.java:396)
	at fr.paladium.factions.client.map.gui.UIFactionMap.preDraw(UIFactionMap.java:229)
	at fr.paladium.lib.apollon.ui.UI.func_73863_a(UI.java:196)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Arrays.fill(Arrays.java:2903)
	at shadersmod.client.ShadersTex.initDynamicTexture(ShadersTex.java:288)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(DynamicTexture.java:42)
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:28)
	at fr.paladium.factions.client.map.utils.DynamicEditableTexture.<init>(DynamicEditableTexture.java:21)
	at fr.paladium.factions.client.map.gui.UIFactionMap.drawMapLayer(UIFactionMap.java:396)
	at fr.paladium.factions.client.map.gui.UIFactionMap.preDraw(UIFactionMap.java:229)
	at fr.paladium.lib.apollon.ui.UI.func_73863_a(UI.java:196)

-- Screen render details --
Details:
	Screen name: fr.paladium.factions.client.map.gui.UIFactionMap
	Mouse location: Scaled: (256, 142). Absolute: (1280, 708)
	Screen size: Scaled: (512, 284). Absolute: (2560, 1417). Scale factor of 5

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['SK0R3N'/4956192, l='MpServer', x=17414.61, y=2.62, z=12598.74], EntityOtherPlayerMP['XsfJSMtNXqFel'/7884111, l='MpServer', x=17414.00, y=-0.13, z=12597.00]]
	Chunk stats: MultiplayerChunkCache: 81, 82
	Level seed: 0
	Level generator: ID 04 - TerrainControl, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,109,23), Chunk: (at 0,6,7 in 0,1; contains blocks 0,0,16 to 15,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 82672456 game time, 21600 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityZombie['§b10x'/7883897, l='MpServer', x=17415.78, y=2.50, z=12600.22], EntityZombie['§b81x'/7883898, l='MpServer', x=17415.56, y=2.50, z=12599.97], EntityZombie['§b16x'/7883899, l='MpServer', x=17416.09, y=2.50, z=12599.59], EntitySkeleton['§b18x'/7883900, l='MpServer', x=17416.09, y=2.50, z=12599.63], EntityZombie['§b2x'/7883901, l='MpServer', x=17415.63, y=2.50, z=12600.03], EntitySkeleton['§b99x'/7883902, l='MpServer', x=17416.59, y=2.50, z=12600.00], EntityZombie['§b6x'/7883903, l='MpServer', x=17416.28, y=2.50, z=12600.13], EntityZombie['§b14x'/7883891, l='MpServer', x=17415.75, y=2.50, z=12600.13], EntityZombie['§b6x'/7883892, l='MpServer', x=17416.06, y=2.50, z=12599.69], EntityZombie['§b8x'/7883893, l='MpServer', x=17416.22, y=2.50, z=12600.13], EntityZombie['§b394x'/7883894, l='MpServer', x=17416.09, y=2.50, z=12600.24], EntityOtherPlayerMP['XsfJSMtNXqFel'/7884111, l='MpServer', x=17414.00, y=-0.13, z=12597.00], EntityZombie['Zombie'/7883931, l='MpServer', x=17416.19, y=2.97, z=12600.54], EntityClientPlayerMP['SK0R3N'/4956192, l='MpServer', x=17414.61, y=2.62, z=12598.74], EntityZombie['§b6x'/7884050, l='MpServer', x=17415.59, y=2.50, z=12599.91], EntityZombie['§b15x'/7884116, l='MpServer', x=17415.59, y=2.50, z=12599.88], EntityOtherPlayerMP['XsfJSMtNXqFel'/7884111, l='MpServer', x=17414.00, y=-0.13, z=12597.00], EntityXPOrb['Experience Orb'/7883904, l='MpServer', x=17415.77, y=2.75, z=12599.77]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2443)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:920)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9271332760 bytes (8841 MB) / 10737418240 bytes (10240 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 11 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx13G -Xms10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (beaaadcc5114ba2cbd30a46663759c6f7c1033be171dab602a824b2068deda0c) 
	UCHIJA	apollon{4.4.3} [Apollon] (cde433b266f6c0a02fc7ab8f72168567a7e1dc5685642d780912fe2399d10cfb) 
	UCHIJA	backtothefuture{1.0} [Back to the future] (d470b0da7646576b94419d4668ba3062afeabec2637866e280e39b8f472790a3) 
	UCHIJA	cresus{0.1} [Cresus] (154c6190ba1cf4e456c44fd441b74f3214b247a896bf6667f2b6f924bc1df9ec) 
	UCHIJA	customnpcs{1.5.4} [CustomNpcs] (32b73a01e91256aee7ea92fe4e33f17eaa42914111f129a2e2427921447fcbf7) 
	UCHIJA	factions{0.1} [Factions] (c372c1ffdafcfa9eca3b9e5849f8496d483fe8a86ed0a6b14c65f76f555583e0) 
	UCHIJA	helios{2.4.0} [Helios Mod] (0f3692ee8133b5fc77da79257d746ca5e71c06078d2795cf55f4861f26aeedd0) 
	UCHIJA	palamod{7.6.1.2} [PalaMod] (aef2dd854f8512790301bd754dce232b1def54c27b7693b4689e331c5f52bb49) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (30722a5711603c1984b579ad4b60ee4dd1a3eee25d33fe49b08c5cc24937394c) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (f86fdb9d517f3107ddcba66976a319ac68eb95687e999a9f1dadf4fd9cd2d36e) 
	UCHIJA	common{1.0} [Paladium Common] (ea3e31803e033a4824f9edc2b4b2a8af405a0ff38211a0e2bf0ce2a9d4c42060) 
	UCHIJA	palagamemod{1.0} [PalaGame Mod] (f11998c6db2d9288efb43fb31b9cde18d39cb12310a3aa8ecdf5f8be0dc8a468) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (4be2054d3ca56ee86be49c66e632ac752d7528bb3148baae9f50a18216b953f8) 
	UCHIJA	StorageDrawers{1.7.10-1.10.11} [Storage Drawers] (ddc41df8fd394da0fdb4f805ed82a1777d223fb713be97c40c3d4e6fc5fa3826) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (58385363ce4632adb117979a89745f451bceac409fd083e17303b20ed8cd9cdb) 
	Pulsar/common loaded Pulses: 
		- common-cosmetics (Enabled/Forced)
		- common-boutique (Enabled/Forced)
		- common-armourers (Enabled/Forced)
		- common-common (Enabled/Forced)

	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.96, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [BDcraft Sounds Pack.zip, PureBDcraft 128x MC17.zip, [x128] PalaBDcraft (1.7 style).zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 471.96
	OpenGlRenderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
[15:16:35] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\skore\AppData\Roaming\.paladium\crash-reports\crash-2022-07-31_15.16.34-client.txt

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
