### ISSUE TITLE
[Bug]: Crash coordinate jammer

### ISSUE THREAD

**Issue by TT54** [Paladium-Developpement/Paladium-Issue#81]
### Pseudo InGame

TT54

### Que s'est-il passé ?

Plusieurs bases avec un coordinate jammer font crash les joueurs dedans.

### Qu'aurait-il dû arriver ?

On n'aurait pas du crash

### LOG

[18:17:19] [Client thread/INFO]: [Client thread] Client side modded connection established
[18:17:19] [Client thread/INFO]: [fr.paladium.iIIiiiiiiiIiIii:BO:75]: Patching Chunk Loading
[18:17:20] [Client thread/INFO]: [CHAT] [HolographicDisplays] Found an update: v2.4.9. Download:
[18:17:20] [Client thread/INFO]: [CHAT] >> http://dev.bukkit.org/bukkit-plugins/holographic-displays
[18:17:20] [Client thread/INFO]: [CHAT]  
[18:17:20] [Client thread/INFO]: [CHAT] Vous êtes actuellement en mode vanish.
[18:17:20] [Client thread/INFO]: [CHAT]  
[18:17:20] [Client thread/INFO]: [CHAT] §c[§4PalaTrade§c] §r §6You §6have §6joined §6a §6new §6server, §6your §6trade §6requests §6have §6been §6§areactivated§6! §6Press §6§b'P'§6or §6type §6§b/trade §6§6to §6open §6the §6§cPalaTrade §6§6configuration §6menu.palatrade.tradeaccepted= §6Your §6trade §6request §6has §6been §6§aaccepted§6! §6Opening §6of §6the §6trade §6window! 
[18:17:20] [Client thread/INFO]: [fr.paladium.iIIiiiiiiiIIIIi:func_149720_d:28]: fr.paladium.iIiiIiiiiiiIiII@133ae460 - fr.paladium.IiIIIiiiiiiIiii@1f96c26b
[18:17:23] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: fr.paladium.iIiiIiiiiiiIiII cannot be cast to fr.paladium.IiiIIiiiiiIIiii
	at fr.paladium.IiIIIiiiiiiIiii.func_149673_e(vw:15) ~[IiIIIiiiiiiIiii.class:?]
	at fr.paladium.iIIiiiiiiiIIIIi.func_149673_e(us:46) ~[iIIiiiiiiiIIIIi.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5135) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325) ~[blo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:17:24] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 03/12/21 18:17
Description: Unexpected error

java.lang.ClassCastException: fr.paladium.iIiiIiiiiiiIiII cannot be cast to fr.paladium.IiiIIiiiiiIIiii
	at fr.paladium.IiIIIiiiiiiIiii.func_149673_e(vw:15)
	at fr.paladium.iIIiiiiiiiIIIIi.func_149673_e(us:46)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5135)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1000)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fr.paladium.IiIIIiiiiiiIiii.func_149673_e(vw:15)
	at fr.paladium.iIIiiiiiiiIIIIi.func_149673_e(us:46)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5135)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['TT54'/457607, l='MpServer', x=7306,58, y=6,82, z=372,70]]
	Chunk stats: MultiplayerChunkCache: 25, 26
	Level seed: hhh0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 239590476 game time, 217331078 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['TT54'/457607, l='MpServer', x=7306,58, y=6,82, z=372,70]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2443)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1941239760 bytes (1851 MB) / 2852126720 bytes (2720 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -Xms2048M -Xmx6144M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (beaaadcc5114ba2cbd30a46663759c6f7c1033be171dab602a824b2068deda0c) 
	UCHIJA	CarpentersBlocks{3.2.8.7} [Carpenter's Blocks] (29ffadfdc5fbcf7063d831112eecf57e038c7bf7af7d4cf486336c6ef140baef) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (32b73a01e91256aee7ea92fe4e33f17eaa42914111f129a2e2427921447fcbf7) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (dfe1f7022afddb09a46100298a06b70e1b4805be2f03901c270d8758d5b09e35) 
	UCHIJA	props{2.4.2} [Decocraft] (dfe1f7022afddb09a46100298a06b70e1b4805be2f03901c270d8758d5b09e35) 
	UCHIJA	palamod{7.5.2.0} [PalaMod] (aef2dd854f8512790301bd754dce232b1def54c27b7693b4689e331c5f52bb49) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (30722a5711603c1984b579ad4b60ee4dd1a3eee25d33fe49b08c5cc24937394c) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (f86fdb9d517f3107ddcba66976a319ac68eb95687e999a9f1dadf4fd9cd2d36e) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (4be2054d3ca56ee86be49c66e632ac752d7528bb3148baae9f50a18216b953f8) 
	UCHIJA	StorageDrawers{1.7.10-1.10.11} [Storage Drawers] (ddc41df8fd394da0fdb4f805ed82a1777d223fb713be97c40c3d4e6fc5fa3826) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (58385363ce4632adb117979a89745f451bceac409fd083e17303b20ed8cd9cdb) 
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithfull_paladium_officiel.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1650 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
[18:17:24] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\theo5\AppData\Roaming\.paladium\crash-reports\crash-2021-12-03_18.17.23-client.txt

**Comment by TT54** [comment]
J'ai réussi à avoir une petite précision : lorsqu'un joueur pose le coordinate jammer afin qu'il prenne la texture d'un cobble breaker, le jeu crash (j'ai pu tester avec Robin), mais pas sur les différents blocs "normaux" (paladium block, dirt, obsi), ni sur les autres TileEntity (on a testé Palamachine, Crusher, Alchemy Creator). Donc le problème semble venir uniquement du cobble breaker.
