### ISSUE TITLE
[Bug]: Crash lors de l'ouverture du GUI golem

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#986]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on ouvre le GUI de sont golem on crash

### LOG

[16:43:43] [Client thread/ERROR]: OpenGuiHandler exception
java.lang.IllegalArgumentException: Unable to add an inventory who not extends PaladiumInventory (EntityGolem['Guardian Golem'/390168584, l='MpServer', x=20888,00, y=55,00, z=-7254,00])
	at fr.paladium.lib.apollon.container.PaladiumContainer.func_75146_a(PaladiumContainer.java:34) ~[PaladiumContainer.class:?]
	at fr.welsymc.guardiangolem.common.containers.ContainerGolem.<init>(ContainerGolem.java:18) ~[ContainerGolem.class:?]
	at fr.welsymc.guardiangolem.common.utils.GuiHandler.getClientGuiElement(GuiHandler.java:55) ~[GuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:265) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) ~[yz.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:16) ~[OpenGuiHandler.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:11) ~[OpenGuiHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1592) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:963) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:889) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:43:43] [Client thread/ERROR]: HandshakeCompletionHandler exception
java.lang.IllegalArgumentException: Unable to add an inventory who not extends PaladiumInventory (EntityGolem['Guardian Golem'/390168584, l='MpServer', x=20888,00, y=55,00, z=-7254,00])
	at fr.paladium.lib.apollon.container.PaladiumContainer.func_75146_a(PaladiumContainer.java:34) ~[PaladiumContainer.class:?]
	at fr.welsymc.guardiangolem.common.containers.ContainerGolem.<init>(ContainerGolem.java:18) ~[ContainerGolem.class:?]
	at fr.welsymc.guardiangolem.common.utils.GuiHandler.getClientGuiElement(GuiHandler.java:55) ~[GuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:265) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) ~[yz.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:16) ~[OpenGuiHandler.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:11) ~[OpenGuiHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1592) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:963) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:889) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:43:43] [Client thread/ERROR]: There was a critical exception handling a packet on channel FML
java.lang.IllegalArgumentException: Unable to add an inventory who not extends PaladiumInventory (EntityGolem['Guardian Golem'/390168584, l='MpServer', x=20888,00, y=55,00, z=-7254,00])
	at fr.paladium.lib.apollon.container.PaladiumContainer.func_75146_a(PaladiumContainer.java:34) ~[PaladiumContainer.class:?]
	at fr.welsymc.guardiangolem.common.containers.ContainerGolem.<init>(ContainerGolem.java:18) ~[ContainerGolem.class:?]
	at fr.welsymc.guardiangolem.common.utils.GuiHandler.getClientGuiElement(GuiHandler.java:55) ~[GuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:265) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) ~[yz.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:16) ~[OpenGuiHandler.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:11) ~[OpenGuiHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1592) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:963) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:889) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:43:43] [Netty Client IO #5/INFO]: Created 15 type lists for file list type SERVER_PUBLIC.
[16:43:43] [Netty Client IO #5/INFO]: Created 15 type lists for file list type SERVER_PRIVATE.
[16:43:43] [Client thread/INFO]: Applying holder lookups
[16:43:43] [Client thread/INFO]: Holder lookups applied
[16:44:05] [Client thread/INFO]: Connecting to mc.paladium-pvp.fr, 25565
[16:44:05] [Netty Client IO #6/INFO]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, apollon, backtothefuture, chronos, cresus, customnpcs, factions, guardiangolem, helios, IronChest, common, palagamemod, palamod, palapass, secretroomsmod, StorageDrawers, TerrainControl] at SERVER
[16:44:06] [Client thread/INFO]: Connecting to paladium (mc.paladium-pvp.fr:25565)
[16:44:06] [Netty Client IO #8/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S02PacketChat
[16:44:06] [Netty Client IO #8/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S02PacketChat
[16:44:06] [Client thread/INFO]: [CHAT] Chat de modération activé
[16:44:06] [Client thread/INFO]: [CHAT] You have not been moved because you have the playerbalancer.bypass permission
[16:44:06] [Netty Client IO #8/INFO]: Server protocol version 2
[16:44:06] [Netty Client IO #8/INFO]: Attempting connection with missing mods [CodeChickenCore, NotEnoughItems, cresus, customnpcs, factions, guardiangolem, IronChest, palamod, palapass, secretroomsmod, StorageDrawers, TerrainControl] at SERVER
[16:44:06] [Netty Client IO #8/INFO]: Injecting existing block and item data into this client instance
[16:44:06] [Netty Client IO #8/INFO]: Applying holder lookups
[16:44:06] [Netty Client IO #8/INFO]: Holder lookups applied
[16:44:07] [Client thread/INFO]: [Client thread] Client side modded connection established
[16:44:07] [Client thread/INFO]: [fr.paladium.IIIiiiiiiiiiIiI:BN:148]: Patching Chunk Loading
[16:44:07] [Client thread/INFO]: [codechicken.nei.NEIClientConfig:loadWorld:217]: delai NEI: 3ms
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:07] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:16] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:18] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:21] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:26] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:27] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:28] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:35] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:36] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:39] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:44:42] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!
[16:45:03] [Client thread/INFO]: [fr.paladium.common.ClientEventHandler:getDownloadImageSkin:44]: Download skin !!!

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
